apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  description: ${{ values.description | dump }}
  tags:
    - dotnet
  links:
    - url: https://github.com/${{values.destination.owner + "/" + values.destination.repo}}
      title: Source Code
      icon: github
    # - url: https://api.heroes.com
    #   title: Production
    #   icon: globe
  annotations:
    # this could also be `url:<url>` if the documentation isn't in the same location
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner | dump }}
  # system: ${{ values.system | dump }}
  # dependsOn: ['resource:heroes-db']
  # apiConsumedBy: ['component:www-heroes']
